public class SalesOrder_InsuranceDetailWrapper {
    
    public String SID_BRM_COMPCD;
    public String SID_BRM_LOCCD;
    public String SID_BRM_BRCD;
    public String SID_SOH_UNIQUEBRCD;
    public String SID_SOH_FRNCD;
    public String SID_SOH_SONO;
    public String SID_BAM_INSCD;
    public Double SID_NCB;
    public Double SID_PREMIUMAMT;
    public String SID_CREATEDBY;
    public String SID_CREATEDDT;
    public String SID_LASTUPDBY;
    public String SID_LASTUPDDT;
    public Integer SID_PERIOD;
    
    /**
    public String SID_INSREASON;
    public Double SID_COVERAMT;
    public String SID_COVERNOTENO;
    public Double SID_GSTAMT;
    public String SID_TPIS;
    public Double SID_TPISAMT;
    public String SID_INSSTARTDT;
    public String SID_INSEXPDT;
    public String SID_INSPOLICYNO;
    public String SID_SECOMM;
    public String SID_COMMRECDDT;
    public String SID_COMPCOMM;
    public String SID_ENDORSEDT;
    public String SID_ENDORSEINVDT;
    public String SID_REMARKS;
    **/
    
    public SalesOrder_InsuranceDetailWrapper() {
        
        SID_BRM_LOCCD = 'SGD';
           
    }
    
}