import { createElement } from 'lwc';
import Ncl_ShipmentLineItemMatching from 'c/ncl_ShipmentLineItemMatching';

describe('c-ncl-shipment-line-item-matching', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ncl-shipment-line-item-matching', {
            is: Ncl_ShipmentLineItemMatching
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});